### ISSUE TITLE
How to compile

### ISSUE THREAD

**Issue by kuwoh** [FWGS/cs16-client#220]
Sorry if i sound like a complete noob here but
what things do i need to compile this

**Comment by a1batross** [comment]
I don't wrote any instructions and buildscripts for now. 

I compile Android version using NDK r10e, JDK, Android SDK and Google Play Services SDK.
I use outdated Google Play Services library, because newer versions are distributed only by Maven and I don't have free time to configure Maven(but it's in TODO list for cs16client and xash3d both :)).

The main scripts is located in android directory. There is only three scripts: clean, update and build. 
Last one accepts two arguments:
"./build <release|debug> <omp|noomp>"

First switches build type and last one switches OpenMP auto loop parallelization. OpenMP was been a sort of experiment and I don't use it since 1.01.
