### ISSUE TITLE
Is there a way for me to access the launchers sources?

### ISSUE THREAD

**Issue by Lion4K** [FWGS/cs16-client#287]
Together with some friends we are making a mod. Hu3-Life https://www.youtube.com/watch?v=fvkc70QQid0. And we are looking into making it work on mobiles too, but specially into mobiles VR where it will be cheaper to buy the needed hardware, rather than an Expensive Vive.

Our mod will not only feature SinglePlayer but also CO-OP Multiplayer, that why we think a custom launcher will be needed rather than some adaptations for it to run on standard launcher, since it's not just a reskin mod.

We are basing it on HLEnhanced, and so it have all guns from Gearbox, i mean, opposing force, and uses those guns with several functions altered, lot of stuff done.

I tried loading the mod into Xash, it loaded, but, the extra guns from gearbox didn't loaded, so I guess We'll need a custom launcher for it, I was trying to use the opposing force client but i realized that there isn't one right?

So If you could help us with that We would really appreciate.

**Comment by nekonomicon** [comment]
I do not recommend to use HL:Enhanced, because in this sdk was broken support for the old compilers and may be too hard port code from old sdk.

We have own hlsdk fork in hlsdk-xash3d repo with bunch of bugfixes. 

If you need gearbox entities implementation you can check this branch:
https://github.com/LostGamerHL/hlsdk-xash3d/commits/opfor

Launcher template example:
https://github.com/FWGS/mod-sample


Mod porting guide:
https://github.com/FWGS/xash3d/wiki/Mod-Porting-Guide

**Comment by Lion4K** [comment]
Thank you very much!
